# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: "temporalpool"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    echo "CORRIENDO LINT"
    npm run lint
    echo "CORRIENDO PRETTIER"
    npm install --save-dev --save-exact prettier
    npm run prettier
    echo "CORRIENDO TEST"
    CI=true npm test
    echo "CORRIENDO BUILD"
    npm run build
    sudo cat /etc/passwd
    sudo cat /etc/group
    docker version
  displayName: 'npm install and build'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'   

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'

#- task: Docker@2
#  inputs:
#    containerRegistry: 'svc-testullstack'
#    repository: 'testfullstack'
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile'
